# This is a config for E2B sandbox template.
# You can use template ID (6v17s4a1bnl5cbkvit8c) or template name (marcode-nextjs) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("marcode-nextjs") # Sync sandbox
# sandbox = await AsyncSandbox.create("marcode-nextjs") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('marcode-nextjs')

team_id = "d3bd91f8-ec41-4cf4-8d64-2b5ff444afdd"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "marcode-nextjs"
template_id = "6v17s4a1bnl5cbkvit8c"
